"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
exports.ErrorCode = void 0;
var ErrorCode;
(function (ErrorCode) {
    ErrorCode["SUCCESS"] = "00";
    ErrorCode["GENERAL_ERROR"] = "99";
    ErrorCode["BAD_REQUEST"] = "01";
    ErrorCode["EMAIL_INVALID"] = "02";
    ErrorCode["EMAIL_EXISTED"] = "03";
    ErrorCode["INVALID_USERNAME_FORMAT"] = "04";
    ErrorCode["INVALID_PASSWORD_FORMAT"] = "05";
    ErrorCode["ROOM_NOT_EXISTED"] = "06";
    ErrorCode["NAME_IS_TOO_LONG"] = "07";
    ErrorCode["DATE_STRING_INVALID"] = "08";
    ErrorCode["EMAIL_IS_NOT_EMPTY"] = "09";
    ErrorCode["NAME_IS_NOT_EMPTY"] = "10";
    ErrorCode["NAME_IS_NOT_STRING"] = "11";
    ErrorCode["PASSWORD_IS_NOT_EMPTY"] = "12";
    ErrorCode["PASSWORD_IS_NOT_STRING"] = "13";
    ErrorCode["AVATAR_IS_NOT_STRING"] = "14";
    ErrorCode["DESCRIPTION_IS_NOT_STRING"] = "15";
    ErrorCode["ADDRESS_IS_NOT_STRING"] = "16";
    ErrorCode["GENDER_INVALID"] = "17";
    ErrorCode["INVALID_PHONE_NUMBER_FORMAT"] = "18";
    ErrorCode["ADDRESS_IS_TOO_LONG"] = "19";
    ErrorCode["DESCRIPTION_IS_TOO_LONG"] = "20";
    ErrorCode["INVALID_AVATAR"] = "21";
    ErrorCode["FILE_SIZE_TOO_LARGE"] = "22";
    ErrorCode["ROOM_TYPE_INVALID"] = "23";
    ErrorCode["HAS_SEND_MAIL_INVALID"] = "24";
    ErrorCode["END_TIME_MUST_GREATER_THAN_START_TIME"] = "25";
    ErrorCode["START_TIME_MUST_GREATER_THAN_CURRENT_TIME"] = "26";
    ErrorCode["ID_IS_NOT_EMPTY"] = "27";
    ErrorCode["ID_IS_NOT_STRING"] = "28";
    ErrorCode["LIVESTREAM_ROOM_ENDED"] = "29";
    ErrorCode["MEETING_ROOM_CANCELLED"] = "30";
    ErrorCode["CAN_NOT_CANCEL_LIVE_ROOM"] = "31";
})(ErrorCode = exports.ErrorCode || (exports.ErrorCode = {}));
//# sourceMappingURL=errorcode.enum.js.map