export const MESSAGE = {
  MS_1: "This field is required",
  MS_2: "The Meeting ID is invalid",
  MS_3: "The photo is too large (exceeds 5 MB limit)",
  MS_4: "File type is not allowed (only accepts JPG, JPEG, PNG, GIF)",
  MS_5: "Update successfully!",
  MS_6: "Fail to update!",
  MS_7: "Only English characters, numbers, and spaces are allowed ",
  MS_8: "Bad request!",
  MS_9: "Email invalid!",
  MS_10: "Email exists!",
  MS_11: "Invalid username format!",
  MS_12: "Invalid password format!",
  MS_13: "Minimum 8 characters, maximum 30 characters, at least one character, one number",
  MS_14: "Must be less than 30 characters",
  MS_15: "Passwords must match",
  MS_16: "Invalid email format",
  MS_17: "Invalid phone number",
  MS_18: "Must be less than 200 characters",
  MS_19: "Must be less than 1000 characters",
  MS_20: "Phone number is not valid",
  MS_21: "Must be least than 254 characters",
  MS_22: "Invalid birthday",
  MS_23: "Invalid name",
  MS_24:
    "If you input guest's email here, an automatic email with the livestream's link will be sent to their email address",
  MS_25: "You can select up to 3 categories for your livestream room",
  MS_26: "You can only select up to 3 categories.",
  MS_27: "Max length input allow: 500 characters.",
  MS_28: "Must be less than 255 characters",
  MS_29: "Invalid date",
  MS_30: "The End time cannot be earlier than the Start time",
  MS_31: "You cannot select a time in the past",
  MS_32: "There's no account associate with this wallet",
};
